<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>About Our Restaurant</title>
                <style>
                        body {
                                    font-family: Arial, sans-serif;
                                                margin: 0;
                                                            padding: 0;
                                                                    }
                                                                            header {
                                                                                        background-color: #ff7043;
                                                                                                    color: white;
                                                                                                                padding: 1rem;
                                                                                                                            text-align: center;
                                                                                                                                    }
                                                                                                                                            nav a {
                                                                                                                                                        color: white;
                                                                                                                                                                    text-decoration: none;
                                                                                                                                                                                margin: 0 10px;
                                                                                                                                                                                        }
                                                                                                                                                                                                nav a:hover {
                                                                                                                                                                                                            text-decoration: underline;
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                            .content {
                                                                                                                                                                                                                                        padding: 2rem;
                                                                                                                                                                                                                                                    text-align: center;
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                    img {
                                                                                                                                                                                                                                                                                max-width: 400px;
                                                                                                                                                                                                                                                                                            border-radius: 10px;
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                        </style>
                                                                                                                                                                                                                                                                                                        </head>
                                                                                                                                                                                                                                                                                                        <body>
                                                                                                                                                                                                                                                                                                            <header>
                                                                                                                                                                                                                                                                                                                    <h1>About Our Restaurant</h1>
                                                                                                                                                                                                                                                                                                                            <nav>
                                                                                                                                                                                                                                                                                                                                        <a href="index.html">Home</a>
                                                                                                                                                                                                                                                                                                                                                    <a href="about.html">About</a>
                                                                                                                                                                                                                                                                                                                                                            </nav>
                                                                                                                                                                                                                                                                                                                                                                </header>

                                                                                                                                                                                                                                                                                                                                                                    <div class="content">
                                                                                                                                                                                                                                                                                                                                                                            <h2>Welcome to Delicious Bites</h2>
                                                                                                                                                                                                                                                                                                                                                                                    <p>At Delicious Bites, we serve fresh and authentic dishes made with love.
                                                                                                                                                                                                                                                                                                                                                                                               Our mission is to give you an unforgettable dining experience with 
                                                                                                                                                                                                                                                                                                                                                                                                          flavors that take you around the world.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                  <img src="restaurant.jpg" alt="Our Restaurant">
                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                      </body>
                                                                                                                                                                                                                                                                                                                                                                                                                      </html>
                                                                                                                                                                                                                                                                                                                                                                                                                      